### PR TITLE
DOC: some formatting of the docs and new conda install commands

### PR DESCRIPTION
**Pull request by mrakitin**
Here are a few updates to the documentation:
- reformatted the text with vim's `gq`
- updated the `conda install ...` commands to use the patched packages from the [`nsls2forge`](https://anaconda.org/nsls2forge/repo) channel
- removed trailing blank spaces in the code

### CODE REVIEW

**Comment by mrakitin** [comment]
attn @hjjvandam

**Comment by mrakitin** [comment]
I added a few changes, however GH does not display them yet:
```
commit cd8e529ad90971f8b5cdf74597b334a222e9f551 (HEAD -> doc-corrections, origin/doc-corrections)
Author: Maksim Rakitin <mrakitin@bnl.gov>
Date:   Thu Apr 2 16:26:19 2020 -0400

    Parametrize $AUTODOCKTOOLS_UTIL; autodock4.omp -> autodock4
```

**Comment by mrakitin** [comment]
It parametrized all hardcoded paths via the `AUTODOCKTOOLS_UTIL` env variable. Also I renamed `autodock4.omp -> autodock4` as we discussed there is no significant performance boost, and the omp binary does not exist in the conda distribution.

**Comment by mrakitin** [comment]
Thank you, @hjjvandam! I think it can now be merged to master, so the users don't have to switch to this PR branch.

**Comment by hjjvandam** [comment]
Hi Maksim,

I thought I had merged the branch. I’ll will check.

Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by hjjvandam** [comment]
The summary.txt file is no longer correct. I will merge this in nevertheless and fix this file with a subsequent commit.

**Pull request merged**
