### PR TITLE
Convert ProcessingScripts/README to README.md

### PR DESCRIPTION
**Pull request by mrakitin**
This update is to convert the original `README` file in the `ProcessingScripts` directory to the markdown formatted `README.md` file. The rendered form can be found at https://github.com/mrakitin/DataCrunching/blob/c5305e27075e2c3ce68d9d9cd9f1a7e476023b10/ProcessingScripts/README.md. I think #6 should be merged first, then I can apply the formatting to the piece of documentation @xhqu1981 provided.

### CODE REVIEW

**Comment by hjjvandam** [comment]
The changes look good to me, but at the moment git complains about conflicts. I think you are best placed to resolve those.

**Comment by xhqu1981** [comment]
> I can apply the formatting to the piece of documentation @xhqu1981 provided.

Thank @mrakitin so much.

**Comment by mrakitin** [comment]
Done. I rebased on master, resolved the conflicts and applied some extra formatting. Unfortunately, GitHub didn't recognize the change as a rename of the file, so the changes are displayed as new, but they are based on the previous file.

**Comment by mrakitin** [comment]
Thank you, Huub.

**Pull request merged**
